<a href="https://colab.research.google.com/github/conquerv0/Pynaissance/blob/master/1.%20Basic%20Framework/Numpy_Guide.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Computation with NumPy**

Built-in array based object such its limited features rendered it less performance-oriented that the more specialized NumPy arrays. This module will illustrate some powerful features of NumPy that makes this class highly useful in quantitative finance. 

**1. Basic Operation**


In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
a
new_a = np.arange(2, 20, 2)
new_a

a[:2]

# The sum of all elements in the array.
a.sum()

# The standard deviation of the elements.
a.std()

# The cumulative sum of all elements (starting at index 0)
a.cumsum()

array([ 1,  3,  6, 10, 15, 21])

**2. NumPy Vectorized Operation**

Most importantly, **ndarray** objects define mathematical operations for vectorized objects, and have high performance for universal functions on the array.

In [ ]:
np.exp(a)
np.sqrt(a)
np.sqrt(2.5)
# Although math.sqrt(2.5) effectively complete the same thing as above. It cannot be applied to a ndarray object directly

import math
# math.sqrt(a)

# We can apply magic command to time the universal function in the different packages to compare performance.
%timeit np.sqrt(8)
%timeit math.sqrt(8)

The slowest run took 18.64 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.07 µs per loop
The slowest run took 31.28 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 74.7 ns per loop


**3. Multi-Dimensional Operations**

In [ ]:
v = np.array([a, a*2])

# Indexing the second row
v[1]

# Indexing the second column.
v[:, 1]

# Calculate the sum of all values
v.sum()

# Calculate the sum along the first axis
v.sum(axis=0)

# Calculate the sum along the second axis.
v.sum(axis=1)

To use ndarrays, we usualy setup the arrays, then populate it with data points later. 

In [ ]:
# Populating ndarrays.

# Creates a ndarray prepopulated with zeroes
b = np.zeros((2, 3), dtype='i', order='C')
c = np.zeros_like(b, dtype='f16', order='C')
c

# Creates an ndarray object with anything (depends on the bits present in the memory)
d = np.empty((2,3,2))
e = np.empty_like(c)
e

# Creates a sqaure matrix as an ndarray object with the diagonal populated by ones
f = np.eye(5)
f

# Creates a one-dimensional ndarray object with evenly spaced intervals between numbers; 
# parameters: start, end, and num(of elements)
g = np.linspace(8, 16, 20)
g

array([ 8.        ,  8.42105263,  8.84210526,  9.26315789,  9.68421053,
       10.10526316, 10.52631579, 10.94736842, 11.36842105, 11.78947368,
       12.21052632, 12.63157895, 13.05263158, 13.47368421, 13.89473684,
       14.31578947, 14.73684211, 15.15789474, 15.57894737, 16.        ])

In [ ]:
# Useful attributes

# The number of elements
g.size 

# The number of bytes used to represent one elements
g.itemsize

# The number of dimensions
g.ndim

# The shape of the ndarray object.
g.shape

**4. Reshaping and Resizing**

Despite its immutable nature, there are mean to reshape and resize such object. Reshaping usualy provides another view on the data, while resizing generally creates a temporary object to work with.

In [ ]:
h = np.arange(16)
h.shape

np.shape(h)

h.reshape((2, 8))
k = h.reshape((8,2))
k

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])